#!/usr/bin/env python
from megapi import *
from socket import *

bot = MegaPi()
bot.start('/dev/ttyS0')
s=socket(AF_INET, SOCK_DGRAM)
s.setsockopt(SOL_SOCKET, SO_BROADCAST, 1)

while 1:
    bot.gasSensorRead(7,onGas)

def onRead(a):
    s.sendto('gas:'+a,('255.255.255.255',12346))
